[package]
name = "rust-redis-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
threadpool = "1.8"
uuid = { version = "1.2", features = ["v4"] }
serde_json = "1.0"